name: Window 10

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Connect to Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Admin Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)

    - name: Display Tailscale IP
      run: |
        $ip = (tailscale ip -4)
        Write-Host "=============================================="
        Write-Host "CONNECT TO RDP AT: $ip"
        Write-Host "Username: runneradmin"
        Write-Host "Password: @cyb3rking"
        Write-Host "=============================================="

    - name: Keep Runner Alive
      run: |
        while ($true) {
            Start-Sleep -Seconds 60
        }
